### ISSUE TITLE
Can't find '__main__' module in 'uncompyle2'

### ISSUE THREAD

**Issue by ghost** [wibiti/uncompyle2#27]
After running "setup.py install" I get the following error message whenever I run "python uncompyle2"

Can't find '**main**' module in 'uncompyle2'

**Comment by guru81** [comment]
Hi from BULGARIA see
root@anti-europe:~# python /root/Desktop/1 hello.py
/usr/bin/python: can't find '__main__' module in '/root/Desktop/1'
root@anti-europe:~# python /root/Desktop/1/hello.py
George Sariev
root@anti-europe:~# 

DONT'T USE SPACE USE "/"
