### ISSUE TITLE
Get error: TypeError: main() takes at most 8 arguments (10 given) Edit

### ISSUE THREAD

**Issue by lzq8272587** [wibiti/uncompyle2#33]
HI, everyone:

I try to install uncompyle2 by using "python setup.py install"

and after that I use "uncompyle2 file.pyc" to decompile.

BUT I got this error:

2013.12.30 11:26:17 CST
Traceback (most recent call last):
File "/usr/local/bin/uncompyle2", line 166, in 
showasm, showast, do_verify, py, deob)
TypeError: main() takes at most 8 arguments (10 given)

My OS is Ubuntu13.10. May anyone offer me some tips to address this problem?

Thanks!!

**Comment by wibiti** [comment]
I can't reproduce this error.
