### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rdoursenaud** [wibiti/uncompyle2#40]
I'm creating an Arch Linux package for the AUR and I'm a bit puzzled by the licensing informations provided.

https://github.com/wibiti/uncompyle2/blob/master/PKG-INFO says GPLv3

But all other files state to refer to the main module (https://github.com/wibiti/uncompyle2/blob/master/uncompyle2/__init__.py) which holds an MIT license.

I believe the source code has priority and PKG-INFO is wrong.

**Comment by rocky** [comment]
In [uncompyle6](https://pypi.python.org/pypi?name=uncompyle6&:action=display) I made the correction to [PKG-INFO](https://pypi.python.org/pypi?name=uncompyle6&version=2.3.2&:action=display_pkginfo). 

Previously I had contacted all of the previous authors to get confirmation, and the MIT license is correct.

BTW uncompyle6 also supports bytecode for some Python 3 as well as Python 2. This repo hasn't had a commit made in quite a while.

**Comment by wibiti** [comment]
changed the PKG-INFO to show MIT license
