### ISSUE TITLE
Handling docstrings with embedded triple quotes

### ISSUE THREAD

**Issue by rocky** [wibiti/uncompyle2#43]
This code with embedded triple quotes isn't handled properly.

```
r'''func placeholder - with ("""\nstring\n""")'''
def foo():
    r'''func placeholder - ' and with ("""\nstring\n""")'''

def bar():
    r"""func placeholder - ' and with ('''\nstring\n''') and \"\"\"\nstring\n\"\"\" """
```

A possible patch is: 

https://github.com/rocky/python-uncompyle6/commit/805e17988edbf28ebd61d0d65e05d569802c0ca4

**Comment by wibiti** [comment]
Fixed with this, https://github.com/wibiti/uncompyle2/commit/b222c577c038a66f7d13bd234904a467e194c1fd
