### ISSUE TITLE
Two corner cases

### ISSUE THREAD

**Issue by feisuzhu** [wibiti/uncompyle2#44]
```python
# https://github.com/remoun/python-protobuf/blob/master/google/protobuf/internal/encoder.py#L75
print 1e10000

# https://github.com/tomerfiliba/rpyc/blob/master/rpyc/core/netref.py#L28
print (1).__add__
```

Which decompyles to 

```python
print inf
print 1.__add__
```

**Comment by rocky** [comment]
Um, this is not a bug. The measure of correct measure of compilation is whether it captures the semantics of the bytecode it was given, not that it matches the source code that was used to create it. 

See https://github.com/rocky/python-uncompyle6/blob/master/README.rst#known-bugsrestrictions for an elaboration of why you can't always reconstruct the source code exactly. 

A disassembly of those instructions in Python 2.7 is: 

```
  2           0 LOAD_CONST               0 (inf)
              3 PRINT_ITEM
              4 PRINT_NEWLINE

  5           5 LOAD_CONST               1 (1)
              8 LOAD_ATTR                0 (__add__)
             11 PRINT_ITEM
             12 PRINT_NEWLINE
             13 LOAD_CONST               2 (None)
             16 RETURN_VALUE
```

And what you report is the decompilation matches that code exactly
